### ISSUE TITLE
Unable to get REST API token if IDP enabled

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/idp-addon#14]
### Environment

- Platform version: 7.1+
- Addon version: 0.2+
- Client type: Web, REST API

### Description of the bug or enhancement

- Minimal reproducible example

1. Create a project
2. Add REST API and IDP Add-ons
3. Configure IDP
4. Try to obtain REST API access token

- Expected behavior

A response with an access token is returned

- Actual behavior

Empty response is returned (in fact redirected)

### Proposal

It seems that we can easily fix the problem with the following change in the `BaseIdpSessionFilter` class:

```Java
if (session.getAttribute(IDP_SESSION_ATTRIBUTE) == null) {
    if ("GET".equals(httpRequest.getMethod())
            && !StringUtils.startsWith(httpRequest.getRequestURI(), httpRequest.getContextPath() + "/PUSH")) {
        httpResponse.sendRedirect(getIdpRedirectUrl(httpRequest));
    } else {
        chain.doFilter(request, response);
    }
    return;
}
```

### Test project

To be able to test the case you can use the [idp-rest-demo](https://github.com/cuba-labs/idp-rest-demo/tree/feature/platform-7) project

**Comment by BryanYin** [comment]
Hi @dtsaryov , do we have any expected fix time for this issue?

**Comment by dtsaryov** [comment]
Hi @BryanYin 

Unfortunately I am no longer responsible for the addon.

@zaharchenko-evgeny please pay attention

**Comment by BryanYin** [comment]
In addition, if REST API enabled anonymous access, i.e. `cuba.rest.anonymousEnabled = true`, GET request will fail and redirect to login page.

**Comment by Desire456** [comment]
Can't reproduce it on CUBA version 7.2.13, IDP addon version 0.3

**Comment by maistrenkoIulia** [comment]
CUBA Platform version: 7.2-SNAPSHOT
CUBA Studio plugin version: 15.0.SNAPSHOT2738-211
IntelliJ version: IntelliJ IDEA 2021.2 (Community Edition)
send http://localhost:8080/app/rest/v2/oauth/token?grant_type=password&username=admin&password=admin
Authorization: Basic Y2xpZW50OnNlY3JldA==
Content-Type: application/x-www-form-urlencoded
User-Agent: PostmanRuntime/7.28.2
Accept: */*
Postman-Token: f03eb6e5-f47d-42cd-9d4c-22f774db0f70
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 46
Cookie: JSESSIONID=20EF3AFD1079E062C93C85637D54B420
AR:
JSONError: No data, empty input at 1:1

**Comment by maistrenkoIulia** [comment]
verified
